/** @jsxImportSource @emotion/react */
import { css } from "@emotion/react"
import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import TopBar from "@/components/Topbar";
import BottomBar from "@/components/BottomBar";
import PlantCard from "@/components/PlantCard";
import 'bulma/css/bulma.css'
import { SignInButton, SignedIn, SignedOut } from "@clerk/nextjs";



export default function Home() {
  function burgerActive(){
    const navbarMenu = document.querySelector('#nav-links')
    navbarMenu.classList.toggle('is-active')
  }
  return (
    <>
      <Head>
        <title>Plant app idk</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <script src='../modules/hamburger.js'></script>
      </Head>
      <main>
        
        <div class='container'>
          <nav class='navbar is-fixed-top is-dark' role="navigation" aria-label="main navigation">
            <div class='navbar-brand'>
            <a class="navbar-item">
              YOOOOOO PLANT APP
            </a>
              <a class='navbar-burger' id='burger' onClick={burgerActive}>
                    <span></span>
                    <span></span>
                    <span></span>
              </a>
            </div>
            <div class='navbar-menu ' id='nav-links'>
              <div class='navbar-end '>
                <a class='navbar-item '>Settings</a>
                <a class='navbar-item '>
                  <SignedIn>Welcome User!</SignedIn>
                  <SignedOut>
                    <SignInButton></SignInButton>
                  </SignedOut>
                </a>
              </div>
            </div>
          </nav>
          <div class='section'>
            <div class='columns'>
              <PlantCard></PlantCard>
              <PlantCard></PlantCard>
              <PlantCard></PlantCard>
              <PlantCard></PlantCard>
              <PlantCard></PlantCard>
            </div>
          </div>
        </div>
        
      </main>
    </>
  );
}
